### ISSUE TITLE
Current page is reset to 1 on page load

### ISSUE THREAD

**Issue by muhammetsait** [codenaz/react-paginator#18]
Hi! I was using this lib with Nextjs and I noticed that if the user requests a page like this:

`localhost:3000/products?page=2`

`page=2` is loaded and then immediately setCurrentPage(1) callback is called, which causes `page=1` to load instead.

I think it would be better if the paginator was able to keep the current page without going back to page=1 on first load.

**Comment by codenaz** [comment]
The Paginator component takes a currentPage prop, so you can write a useEffect or any logic that extracts the page you want   to send the user to from your URL or anywhere else your app stores that data, and pass it to the currentPage prop. How you implement this is up to you since your app has access to update the currentPage prop.

**Comment by muhammetsait** [comment]
Hi! sorry for the late response.

I'm actually passing the currentPage, but it still goes to the first page anyway. I think the problem may be related to those lines in `paginator.js`:

```javascript
  useEffect(() => {
    gotoPage(1);
  }, [gotoPage]);
```
it always calls gotoPage(1) first regardless of the value of currentPage prop.

**Comment by codenaz** [comment]
I see. The component goes to page one on the initial load. Delay setting
currentPage on your app till after the component has loaded. I will push a
fix for this soon

**Comment by vikasg603** [comment]
Hey, @codenaz, any update on this issue?
I am getting lot's of the issue on NextJS because of this.

**Comment by TrejoCode** [comment]
@codenaz Any update? Please.

**Comment by codenaz** [comment]
#30 
This PR addresses the issue.
