### ISSUE TITLE
It is overwriting all my application styles. how to resolve this issue ?

### ISSUE THREAD

**Issue by srikanthpathlavath** [codenaz/react-paginator#3]
First Image with paginator and second image without paginator.

![Screenshot (60)](https://user-images.githubusercontent.com/47449366/63854314-8a208d80-c9ba-11e9-95da-85e312eafb9b.png)
![Screenshot (61)](https://user-images.githubusercontent.com/47449366/63854315-8a208d80-c9ba-11e9-8cc2-fbe1e746e56e.png)

**Comment by srikanthpathlavath** [comment]
please react to this issue. how to overcome it?

**Comment by codenaz** [comment]
@srikanthpathlavath I guess it's because this package uses bootstrap, so some of its class names might be conflicting with yours. We might just have to get rid of bootstrap and replace with custom CSS.

**Comment by srikanthpathlavath** [comment]
Sir, I need to use your package, it's very nice and I am using bootstrap external cdn links, what should I do now? what to write in the custom CSS file.

**Comment by codenaz** [comment]
#2

**Comment by codenaz** [comment]
#2 Remove bootstrap

**Comment by codenaz** [comment]
#

**Comment by codenaz** [comment]
This issue is fixed in v0.3.0
