### ISSUE TITLE
Next/Prev buttons optional/configurable

### ISSUE THREAD

**Issue by CShaddick** [codenaz/react-paginator#5]
Hi,
Is there any scope for the Next/Prev buttons could be configurable? It would offer great flexibility to have the option to turn on/off, and possibly add extra classes, to these two buttons as currently the only configuration is their text.

**Comment by rootlinux2** [comment]
Hi, I got this warning on the browser console.
_

> Warning: Received `true` for a non-boolean attribute `next`.
> 
> If you want to write it to the DOM, pass a string instead: next="true" or next={value.toString()}.


_

I'm using the example code, on NPM readme file 

`
 <Paginator
        totalRecords={data.length}
        pageLimit={4}
        pageNeighbours={1}
        setOffset={setOffset}
        currentPage={currentPage}
        setCurrentPage={setCurrentPage}
      />
`

**Comment by codenaz** [comment]
These issues are fixed in the newest release, update to v0.4.0.
