### ISSUE TITLE
Faster Declaration

### ISSUE THREAD

**Issue by gyto23** [codenaz/react-paginator#6]
In this line the assignment going to be done to empty Array 
https://github.com/codenaz/react-paginator/blob/c8b382f7cd8680c4c7b8b11adbc42e7b6170efbf/src/lib/paginator.js#L99

I recommend to remove the variable assignment from above and move it to the following line

https://github.com/codenaz/react-paginator/blob/c8b382f7cd8680c4c7b8b11adbc42e7b6170efbf/src/lib/paginator.js#L108

Basically 
```let pages = range(startPage, endPage);``` which might save ~small~ tiny amount of render 👍

**Comment by codenaz** [comment]
This shouldn't be an issue. Feel free to make an MR though for code concerns like this
