### ISSUE TITLE
Warning on the console about the value of the attribute NEXT

### ISSUE THREAD

**Issue by rootlinux2** [codenaz/react-paginator#7]
Warning: Received `true` for a non-boolean attribute `next`.
![image](https://user-images.githubusercontent.com/24574267/68535558-18e24c80-0312-11ea-9c00-803cff4e001c.png)

My code

` <Paginator
            totalRecords={totalDocs}
            pageLimit={pageLimit}
            pageNeighbours={2}
            setOffset={() => {}}
            currentPage={currentPage}
            setCurrentPage={setCurrentPage}
          />`

**Comment by codenaz** [comment]
Please, update to the latest version of this package.
